Repository multiverseweb/CodeIt, pull requests merged in 2024-10, with the labels that each got.

#24 Solved Issue
  index.html
  pages/infinity.html
  pages/obfuscation.html
  pages/refine.html
  pages/timeComplexity.html
  resources/common_functions.js
  resources/style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#25 #23 Enhance Dark Mode Consistency and Add Animation to "Scroll to Know More" Icon
  index.html
  resources/home-style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#33 Updated the theme bug
  index.html
  pages/infinity.html
  pages/obfuscation.html
  pages/refine.html
  pages/timeComplexity.html
  resources/common_functions.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#39 Modified contribute button for light mode
  resources/home-style.css
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#57 Issue resolved, theme problem on time-complexity-analyzer page #18
  index.html
  pages/infinity.html
  pages/obfuscation.html
  pages/refine.html
  pages/timeComplexity.html
  resources/analyser.js
  resources/common_functions.js
  resources/style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#73 Added social media icons
  index.html
  resources/style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#80 updated links for socials
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#77 A minimum character limit enforced to feedback form
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#85 Add feature license section Issue #62
  images/license.png
  index.html
  resources/home-style.css
  resources/homeScript.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#131 Change UI of button
  resources/home-style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#120 Resolved issue Nav items overflown towards right #68
  index.html
  resources/homeScript.js
  resources/navbar.js
  resources/style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#129 Fix navigation to feedback form
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#175 Issue #165 resolved: clear code button
  resources/common_functions.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#169 chatbot has been added ✨
  .DS_Store
  index.html
  pages/infinity.html
  pages/obfuscation.html
  pages/refine.html
  pages/timeComplexity.html
  resources/home-style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#162 add featured in table in main readme.md file
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#179 copyright is now dynamic>
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#155 fix : console errors
  resources/homeScript.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#154 Create greetings.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#191 File Uploading Option Added in TimeComplexity Analyser
  pages/timeComplexity.html
  resources/style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#198 Footer UI improvement
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#203 Added Typescript , Php , Go and C# to Code Refiner
  resources/refine.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#208 Light mode/fix (Fixes #164 )
  index.html
  resources/common_functions.js
  resources/home-style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#58 Issue 55
  .vscode/settings.json
  index.html
  resources/home-style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, Further Improvement Required

#216 Revert "Light mode/fix (Fixes #164 ) "
  index.html
  resources/common_functions.js
  resources/home-style.css
Labels: gssoc-ext, hacktoberfest-accepted

#219 Fixed #192 Time complexity Graph improved
  package.json
  resources/analyser.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#241 Fixed scroll button
  resources/homeScript.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#220 Updated boldness of heading
  resources/home-style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#230 Extd7
  index.html
  resources/style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#245 Update README.md
  README.md
Labels: gssoc-ext, level3, hacktoberfest-accepted

#236 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#250 Add CONTRIBUTION.md File #243
  CONTRIBUTION.md
Labels: gssoc-ext, level2, hacktoberfest-accepted, Further Improvement Required

#267 Fix issue #172 Added contribution Pge
  index.html
  pages/contributorsSection.css
  pages/contributorsSection.html
  pages/contributorsSection.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#269 Changes Done
  index.html
  resources/style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#253 CSS Style for #output_code Textarea
  pages/refine.html
  resources/style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#279 Add Bug Report, Enhancement Request, Documentation Update template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation-update.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: gssoc-ext, level2, hacktoberfest-accepted

#286 Resizing Font Size
  resources/home-style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#287 Auto label workflow automation 🚀
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level3, hacktoberfest-accepted
