Repository multiverseweb/CodeIt, pull requests merged in 2024-11, with the labels that each got.

#291 Automation of project structure updation using GitHub workflows and Python scripts
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: gssoc-ext, level3, hacktoberfest-accepted

#295 Added meta tags to improve SEO and social media sharing features.
  index.html
Labels: gssoc-ext, level2

#300 Adding star rating feature to the feedback section
  index.html
  resources/home-style.css
  resources/style.css
Labels: gssoc-ext, level2

#298 Create sitemap.xml
  sitemap.xml
Labels: gssoc-ext, level3

#311 Improve Contributors page done ! #307
  resources/contributorsSection.js
Labels: gssoc-ext, level2

#309 added scroll to reveal animation to the home page
  index.html
Labels: level3

#310 "Feature : Progress bar added in home page & contributors page"
  index.html
  pages/contributorsSection.html
  resources/contributorsSection.css
  resources/contributorsSection.js
  resources/style.css
Labels: gssoc-ext, level2

#314 Revert ""Feature : Progress bar added in home page & contributors page""
  index.html
  pages/contributorsSection.html
  resources/contributorsSection.css
  resources/contributorsSection.js
  resources/style.css
Labels: gssoc-ext

#317 Create a responsive Total Contributions section done ! #312
  resources/contributorsSection.js
Labels: gssoc-ext, level2

#330 Contributors page redesigned
  pages/contributorsSection.html
  resources/contributorsSection.css
  resources/contributorsSection.js
Labels: gssoc-ext, level3

#328 "Progressbar"
  index.html
  resources/contributorsSection.css
Labels: gssoc-ext, level2

#331 Solved Issue #301 (Bug in GUI in mobile view)
  index.html
  resources/home-style.css
Labels: gssoc-ext, level3

#336 Add Visitor Counter feature done ! #218 #261 #320 ✨✨✨
  index.html
Labels: gssoc-ext, level3

#337 Hide the feedback error while it is not selected.
  index.html
  resources/homeScript.js
Labels: gssoc-ext, level1

#333 Solve bug in cursor pointing
  resources/contributorsSection.css
Labels: gssoc-ext, level1

#339 Made changes in the footer in light mode
  index.html
  resources/home-style.css
Labels: gssoc-ext, level2

#342 Adjusted feedback form.
  index.html
  resources/styles/home-style.css
  resources/styles/style.css
Labels: Further Improvement Required
